---
abstract: 'form validation'
author:
  - 'Masahiro Chiba <nihen@megabbs.com>'
build_requires:
  DBICx::TestDatabase: 0
  DBIx::Class: 0
  DBIx::Class::Schema: 0
  Data::Visitor::Callback: 0
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::Fixture::DBIC::Schema: 0
  Test::LoadAllModules: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FormValidator-Nested
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  MooseX::AttributeHelpers: 0
  MooseX::Types::Path::Class: 0
requires:
  Any::Moose: 0
  Class::Param: 0
  DateTime: 0
  DateTime::TimeZone: 0
  Hash::Merge: 0
  Lingua::JA::Regular::Unicode: 0
  List::MoreUtils: 0
  MouseX::AttributeHelpers: 0
  MouseX::Types::Path::Class: 0
  Path::Class: 0
  UNIVERSAL::require: 0
  YAML::Syck: 0
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
